### ISSUE TITLE
Feature Request: Click route to open Map

### ISSUE THREAD

**Issue by PanoramicPanda** [SaltContainer/PokemonEmeraldMapRandoTracker#1]
After putting markers down, it'd be cool to be able to click (maybe shift+click?) to open the map of where it goes rather than finding it in the upper listing.

Similarly, maybe for the ones that should be unique (like gym/e4 markers), marking them off if you've placed them and shift+clicking them opens the map they were marked on.

**Comment by SaltContainer** [comment]
I'll be making a standalone app instead of an EmoTracker pack in the future. This will make features like this possible since I don't think EmoTracker can currently detect shift clicks.
